### ISSUE TITLE
error message: out of memory

### ISSUE THREAD

**Issue by InaJung1** [datascience-mobi/2021-topic-04-team-04#30]
Hey, I was trying to run seed detection, region growing and region merging for one image but I got the error message: out of memory
There is not enough memory to perform the requested operation. Please increase 'Xmx' setting and restart the IDE for change to take effect.
Can I just put in a higher number for Xmx or do I have to change something in my computer settings. I tried to google the problem and fix it myself but I wasn't able to solve the problem.
![PHOTO-2021-06-24-14-33-19](https://user-images.githubusercontent.com/82576388/123279534-3a547400-d508-11eb-9f9f-6e05c7d371af.jpg)

**Comment by npeschke** [comment]
yeah thats a PyCharm thing. Depending on the amount of RAM in your machine you can probably increase it to ~2000-4000 MB.

**Comment by InaJung1** [comment]
Hey, I tried to increase the Xmx on my computer. But it still doesn't run the code. We also tried it on another computer but we got the same problem there. Is there another possibility to solve this problem? Or is it possible to run the code via a VPN on a computer from the university (the physic students can make that)?

**Comment by npeschke** [comment]
Sorry for the late reply, the power supply of my PC thought it is a nice idea to stop working but whenever I tested it, it would work fine.
A few questions to help me debug:

- What script did you run exactly? I'll run it on my machine and look how much memory it takes on my side.
- How much memory do you have in your system?
- What is your current value of Xmx?
- Is it a jupyter notebook or does it show many many plots in SciView? This might cause some heavy memory usage on the PyCharm side.

**Comment by InaJung1** [comment]
We tried to run the code in Unused_ideas_Marie.ipynb. The code is the same as in the python file region_merging. We included a counter to check how many times it runs the loop.
I have 8 GB RAM and in the moment my Xmx value is 4000.
The only output beside the counter in this file is the merged image.
Thanks al lot for your help.

**Comment by npeschke** [comment]
I have no memory issues when running that notebook, even when runningn on the entire image.
PyCharm uses on my side always lower than 1GB of heap memory.

You could try invalidating caches and restart
https://www.jetbrains.com/help/pycharm/invalidate-caches.html
This is one go-to tool to fix weird behavior in PyCharm.

**Comment by InaJung1** [comment]
Hey, the image has now run through half without any error. I will let it run during the night and inform you tomorrow. Thank you very much for your help!

**Comment by npeschke** [comment]
Sounds good, good luck :)

**Comment by InaJung1** [comment]
The code runs through and I was able to save the image. When starting another image, I got an error but I will try it tonight after deleting the cache again.

**Comment by InaJung1** [comment]
So I was able to run region growing tonight. Now I wanted to start region merging but I instantly got this message: Unable to allocate 33.0 GiB for an array with shape (66518, 66518) and data type float64.
I think the problem is that we have too many seeds, do you have any idea what we can make to solve this problem. Is there any datatype that needs less memory? We need two arrays one to store the neighbors and one to store intensity distances, so 3 or 4 decimal places.
I tried to use some filters and image clipping but the result was always worse than without filtering.

**Comment by npeschke** [comment]
for what is the (66518, 66518) array needed exactly?

Yes there are dtypes like a 32 bit float which takes half the space of a 64 bit float.

**Comment by InaJung1** [comment]
The array is there to store the neighbors of every region and its intensity to only merge neighboring regions.

**Comment by npeschke** [comment]
Did you trace back the error message to a position in the code?

**Comment by InaJung1** [comment]
We solved the problem now with reducing the number of seeds. Thank you:)
